#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f $HOME/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
fi

# Find the wallpaper name based on THEMEIS
if [ "$THEMEIS" != "dark.css" ]; then
    wallpaper=$(awk '/swww img/ {count++} count == 1 {gsub("swww img ", ""); sub(".*/", "", $0); print; exit}' ~/.config/hypr/scripts/bgaction)
else
    wallpaper=$(awk '/swww img/ {count++} count == 2 {gsub("swww img ", ""); sub(".*/", "", $0); print; exit}' ~/.config/hypr/scripts/bgaction)
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css

#set the swaync theme
ln -sf $HOME/.config/swaync/style/style$SWITCHTO.css $HOME/.config/swaync/style.css
swaync-client -rs

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Qogir$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
gsettings set org.gnome.desktop.interface icon-theme "Qogir$SWITCHTO"

#change the background image and be cool about it ;)
swww img ~/.config/hypr/backgrounds/$wallpaper --transition-fps 60 --transition-type wipe --transition-duration 2
$HOME/.local/bin/pywal

#update the sddm image
# ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg
ln -sf /usr/share/sddm/themes/sugar-candy/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sugar-candy/wallpaper.jpg

#restart the waybar
killall -SIGUSR2 waybar
