#!/bin/bash

# Get the provided filename
imv_current_file="$1"

# Extract filename
filename=$(basename -- "$imv_current_file")

# Check theme based on stylesheet
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

# Set wallpaper with transition effects
swww img ~/.config/hypr/backgrounds/$filename --transition-fps 40 --transition-type wipe --transition-duration 2

# Update correct line in bgaction file based on theme
if [ "$THEMEIS" == "dark.css" ]; then
    sed -i "0,/swww img/{s/swww img.*/swww img ~\/.config\/hypr\/backgrounds\/$filename/}" ~/.config/hypr/scripts/bgaction
else
    sed -i "0,/swww img/!{s/swww img.*/swww img ~\/.config\/hypr\/backgrounds\/$filename/}" ~/.config/hypr/scripts/bgaction
fi

# Optionally call pywal (comment out if not needed or causing issues)
~/.local/bin/pywal

exit 0
